# -*- coding: utf-8 -*-
"""first_pyspark_program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1imnHM7yVBSs5PCQ6Hsmgv_oJzlh8zMDF

# ***Testing the Programming***

**Downloading "retailstore.csv" from github to our local environment**
"""

!wget https://raw.githubusercontent.com/futurexskill/bigdata/master/retailstore.csv

"""**Installing Spark** """

!wget https://downloads.apache.org/spark/spark-3.1.1/spark-3.1.1-bin-hadoop2.7.tgz

!tar -xvf spark-3.1.1-bin-hadoop2.7.tgz

import os

os.environ["JAVA_HOME"]="/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"]="/content/spark-3.1.1-bin-hadoop2.7"

!pip install findspark

import findspark

findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

!ls

csvData=spark.read.csv("retailstore.csv", header=True)

type(csvData)

csvData.show()